name: Code Styling Workflow
on:
  pull_request:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Laravel Pint
        uses: aglipanci/laravel-pint-action@2.4
        with:
          preset: laravel
          configPath: "pint.json"
          pintVersion: 1.14
      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: Fix styling
          skip_fetch: true
